// Generated by Style Dictionary from design-tokens/tokens.json.
// DO NOT EDIT BY HAND. Run `npm run build` in design-tokens/ to regenerate.

import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Color
  static const Color colorCream = Color(0xFFF5F0E6);
  static const Color colorCreamDeep = Color(0xFFEDE6D9);
  static const Color colorInk = Color(0xFF1C1A17);
  static const Color colorInkSoft = Color(0xFF3F3B35);
  static const Color colorMuted = Color(0xFF6B6359);
  static const Color colorAmber = Color(0xFFB8642A);
  static const Color colorAmberDeep = Color(0xFF944C1B);
  static const Color colorRule = Color(0xFFD9D1C2);

  // Spacing
  static const double spacingXs = 4;
  static const double spacingS = 8;
  static const double spacingM = 16;
  static const double spacingL = 24;
  static const double spacingXl = 32;

  // Radius
  static const double radiusCard = 18;

  // Typography
  static const TextStyle typographyDisplay = TextStyle(fontSize: 32, fontWeight: FontWeight.w700, fontFamily: 'serif');
  static const TextStyle typographyTitle = TextStyle(fontSize: 22, fontWeight: FontWeight.w600, fontFamily: 'serif');
  static const TextStyle typographySubtitle = TextStyle(fontSize: 17, fontWeight: FontWeight.w600, fontFamily: 'serif');
  static const TextStyle typographyBody = TextStyle(fontSize: 15, fontWeight: FontWeight.w400);
  static const TextStyle typographyBodyStrong = TextStyle(fontSize: 15, fontWeight: FontWeight.w600);
  static const TextStyle typographyCallout = TextStyle(fontSize: 13, fontWeight: FontWeight.w400);
  static const TextStyle typographyCalloutStrong = TextStyle(fontSize: 13, fontWeight: FontWeight.w600);
  static const TextStyle typographyMeta = TextStyle(fontSize: 11, fontWeight: FontWeight.w600);

}
