// Generated by Style Dictionary from design-tokens/tokens.json.
// DO NOT EDIT BY HAND. Run `npm run build` in design-tokens/ to regenerate.

import SwiftUI

public enum DesignTokens {
    // MARK: - Color
    public static let colorCream = Color(red: 0.961, green: 0.941, blue: 0.902)
    public static let colorCreamDeep = Color(red: 0.929, green: 0.902, blue: 0.851)
    public static let colorInk = Color(red: 0.110, green: 0.102, blue: 0.090)
    public static let colorInkSoft = Color(red: 0.247, green: 0.231, blue: 0.208)
    public static let colorMuted = Color(red: 0.420, green: 0.388, blue: 0.349)
    public static let colorAmber = Color(red: 0.722, green: 0.392, blue: 0.165)
    public static let colorAmberDeep = Color(red: 0.580, green: 0.298, blue: 0.106)
    public static let colorRule = Color(red: 0.851, green: 0.820, blue: 0.761)

    // MARK: - Spacing
    public static let spacingXs: CGFloat = 4
    public static let spacingS: CGFloat = 8
    public static let spacingM: CGFloat = 16
    public static let spacingL: CGFloat = 24
    public static let spacingXl: CGFloat = 32

    // MARK: - Radius
    public static let radiusCard: CGFloat = 18

    // MARK: - Typography
    public static let typographyDisplay: Font = .system(size: 32, weight: .bold, design: .serif)
    public static let typographyTitle: Font = .system(size: 22, weight: .semibold, design: .serif)
    public static let typographySubtitle: Font = .system(size: 17, weight: .semibold, design: .serif)
    public static let typographyBody: Font = .system(size: 15, weight: .regular, design: .default)
    public static let typographyBodyStrong: Font = .system(size: 15, weight: .semibold, design: .default)
    public static let typographyCallout: Font = .system(size: 13, weight: .regular, design: .default)
    public static let typographyCalloutStrong: Font = .system(size: 13, weight: .semibold, design: .default)
    public static let typographyMeta: Font = .system(size: 11, weight: .semibold, design: .default)

}
