// Style Dictionary build script. Run via `npm run build` in this folder.
// Source: tokens.json. Outputs:
//   - ../ios/NewsletterPodApp/DesignTokens.swift  (consumed by Theme.swift)
//   - dist/tokens.css                             (consumed by the website)

import StyleDictionary from 'style-dictionary';

// Web font stacks for the abstract families used in tokens.json. iOS maps these
// to SwiftUI Font.Design enum cases instead.
const cssFontStack = {
  serif: 'Charter, "Iowan Old Style", "Apple Garamond", Georgia, serif',
  default: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  rounded: 'system-ui, -apple-system, sans-serif',
  monospaced: 'ui-monospace, "SF Mono", Menlo, monospace',
};

// Custom transform: append "px" to spacing/radius/fontSize values for CSS only.
// Source values stay unit-free so Swift emits clean CGFloat / Font.system sizes.
StyleDictionary.registerTransform({
  name: 'size/css-px',
  type: 'value',
  filter: t => ['spacing', 'radius'].includes(t.path[0]) || t.path.includes('fontSize'),
  transform: t => `${Number(t.value)}px`,
});

// Custom transform: rewrite abstract fontFamily values ("serif", "default") to
// a real CSS font stack. Only applies on the web platform.
StyleDictionary.registerTransform({
  name: 'value/css-font-stack',
  type: 'value',
  filter: t => t.path.includes('fontFamily'),
  transform: t => cssFontStack[t.value] ?? t.value,
});

// Custom Swift format: emits SwiftUI Color (not UIColor) for color tokens, and
// CGFloat for spacing/radius tokens. Names follow `<category><PascalName>`,
// e.g. `colorAmberDeep`, `spacingM`, `radiusCard`.
StyleDictionary.registerFormat({
  name: 'swift/design-tokens',
  format: ({ dictionary }) => {
    const lines = [
      '// Generated by Style Dictionary from design-tokens/tokens.json.',
      '// DO NOT EDIT BY HAND. Run `npm run build` in design-tokens/ to regenerate.',
      '',
      'import SwiftUI',
      '',
      'public enum DesignTokens {',
    ];

    const byCategory = (cat) => dictionary.allTokens.filter(t => t.path[0] === cat);
    const colors = byCategory('color');
    const spacings = byCategory('spacing');
    const radii = byCategory('radius');
    const typographyTokens = byCategory('typography');

    if (colors.length) {
      lines.push('    // MARK: - Color');
      for (const t of colors) {
        const { r, g, b } = hexToRgbFloats(t.value);
        const camel = `color${pascal(t.path.slice(1).join('-'))}`;
        lines.push(`    public static let ${camel} = Color(red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)})`);
      }
      lines.push('');
    }
    if (spacings.length) {
      lines.push('    // MARK: - Spacing');
      for (const t of spacings) {
        const camel = `spacing${pascal(t.path.slice(1).join('-'))}`;
        lines.push(`    public static let ${camel}: CGFloat = ${Number(t.value)}`);
      }
      lines.push('');
    }
    if (radii.length) {
      lines.push('    // MARK: - Radius');
      for (const t of radii) {
        const camel = `radius${pascal(t.path.slice(1).join('-'))}`;
        lines.push(`    public static let ${camel}: CGFloat = ${Number(t.value)}`);
      }
      lines.push('');
    }
    if (typographyTokens.length) {
      lines.push('    // MARK: - Typography');
      // Group typography tokens by their style name (path[1]) and emit one
      // SwiftUI Font.system constant per style.
      const styleNames = [...new Set(typographyTokens.map(t => t.path[1]))];
      for (const name of styleNames) {
        const get = (prop) => typographyTokens.find(t => t.path[1] === name && t.path[2] === prop)?.value;
        const size = Number(get('fontSize'));
        const weight = swiftFontWeight(get('fontWeight'));
        const design = swiftFontDesign(get('fontFamily'));
        const camel = `typography${pascal(name)}`;
        lines.push(`    public static let ${camel}: Font = .system(size: ${size}, weight: ${weight}, design: ${design})`);
      }
      lines.push('');
    }

    lines.push('}', '');
    return lines.join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens.json'],
  // The Swift format groups 3 typography tokens (family/weight/size) into one
  // Font constant per style; SD reads that as a name collision and warns.
  // Suppress only that warning — real errors and the verbose log still surface.
  log: { warnings: 'disabled' },
  platforms: {
    ios: {
      buildPath: '../ios/NewsletterPodApp/',
      files: [{ destination: 'DesignTokens.swift', format: 'swift/design-tokens' }],
    },
    web: {
      transformGroup: 'css',
      transforms: ['attribute/cti', 'name/kebab', 'size/css-px', 'value/css-font-stack'],
      buildPath: 'dist/',
      files: [{ destination: 'tokens.css', format: 'css/variables' }],
    },
  },
});

function fmt(n) { return n.toFixed(3); }
function hexToRgbFloats(hex) {
  const h = hex.replace('#', '');
  return {
    r: parseInt(h.slice(0, 2), 16) / 255,
    g: parseInt(h.slice(2, 4), 16) / 255,
    b: parseInt(h.slice(4, 6), 16) / 255,
  };
}
function pascal(s) {
  return s.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}
function swiftFontWeight(value) {
  return ({ '400': '.regular', '500': '.medium', '600': '.semibold', '700': '.bold', '800': '.heavy' })[String(value)] ?? '.regular';
}
function swiftFontDesign(value) {
  return ({ serif: '.serif', default: '.default', rounded: '.rounded', monospaced: '.monospaced' })[value] ?? '.default';
}

await sd.buildAllPlatforms();
console.log('Built design tokens to ../ios/NewsletterPodApp/DesignTokens.swift and dist/tokens.css');
